from pathlib import Path

from devpilot.main import analyze_repository, prepare_analysis
from devpilot.timing import format_duration


def test_non_python_repository_receives_language_aware_maintainability_score(tmp_path: Path) -> None:
    """A JavaScript repository must receive a real code-health signal, not Python-only N/A."""
    (tmp_path / "README.md").write_text("# Frontend\n\n## Overview\nDemo", encoding="utf-8")
    (tmp_path / "index.js").write_text("console.log('hello')", encoding="utf-8")

    report = analyze_repository(tmp_path)

    assert report.code_quality.is_applicable is True
    assert report.code_quality.score > 0
    assert report.language == "JavaScript"
    assert report.code_quality.analyzed_languages == ["JavaScript"]
    assert report.score.overall_score > 0


def test_generated_python_is_excluded_from_maintainability_scope(tmp_path: Path) -> None:
    """Generated protobuf-style code must not distort a repository's source quality signal."""
    (tmp_path / "README.md").write_text("# Demo\n\n## Overview\nDemo", encoding="utf-8")
    (tmp_path / "service_pb2.py").write_text("# Generated by protoc\nvalue = 1\n", encoding="utf-8")

    report = analyze_repository(tmp_path)

    assert report.code_quality.is_applicable is False
    assert report.code_quality.analyzed_files == 0


def test_local_preflight_creates_a_realistic_workload_estimate(tmp_path: Path) -> None:
    """Local paths should be sized before the dashboard starts the visible audit."""
    (tmp_path / "app.py").write_text("def run() -> None:\n    return None\n", encoding="utf-8")

    preflight = prepare_analysis(tmp_path)

    assert preflight.is_remote is False
    assert preflight.scan is not None
    assert preflight.estimate.estimated_seconds >= 4
    assert preflight.estimate.analyzable_python_files == 1
    assert format_duration(75) == "1 min 15 sec"


def test_analysis_emits_progress_and_saves_timing(tmp_path: Path) -> None:
    """The dashboard needs staged progress updates instead of a silent blocking analysis."""
    (tmp_path / "app.py").write_text(
        '"""Demo."""\n\ndef run() -> None:\n    """Run demo."""\n    return None\n',
        encoding="utf-8",
    )
    events = []

    report = analyze_repository(tmp_path, progress_callback=events.append)

    assert events[0].phase == "prepare"
    assert any(event.phase == "code" for event in events)
    assert any(event.phase == "score" for event in events)
    assert events[-1].phase == "complete"
    assert report.analysis_timing.estimated_seconds >= 4
