"""Common helper functions for DevPilot."""

from __future__ import annotations

import re
import shutil
from pathlib import Path

IGNORED_DIR_NAMES = {
    ".git",
    ".hg",
    ".svn",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".tox",
    ".venv",
    "venv",
    "env",
    "node_modules",
    "dist",
    "build",
    ".idea",
    ".vscode",
    "site-packages",
}

TEXT_FILE_SUFFIXES = {
    ".py", ".pyi", ".js", ".mjs", ".cjs", ".jsx", ".ts", ".tsx", ".mts", ".cts",
    ".java", ".c", ".h", ".cpp", ".cc", ".cxx", ".hpp", ".hh", ".hxx", ".cs",
    ".go", ".rs", ".php", ".rb", ".kt", ".kts", ".swift", ".dart", ".scala", ".sc",
    ".r", ".lua", ".sh", ".bash", ".zsh", ".fish", ".ps1", ".psm1", ".psd1", ".sql",
    ".html", ".htm", ".css", ".scss", ".sass", ".less", ".vue", ".svelte", ".ex", ".exs",
    ".clj", ".cljs", ".cljc", ".hs", ".pl", ".pm", ".zig", ".fs", ".fsx", ".m", ".tf",
    ".txt", ".md", ".rst", ".toml", ".cfg", ".ini", ".yaml", ".yml", ".json", ".xml",
    ".env", ".example", ".gradle", ".lock",
}

GITHUB_URL_RE = re.compile(r"^https?://github\.com/[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+/?(?:\.git)?$")


def is_ignored_path(path: Path) -> bool:
    """Return True when a file or folder belongs to a directory that should be skipped."""
    return any(part in IGNORED_DIR_NAMES for part in path.parts)


def is_probably_text_file(path: Path) -> bool:
    """Check whether a file extension is safe to read as text."""
    return path.suffix.lower() in TEXT_FILE_SUFFIXES or path.name.lower().startswith(".env")


def safe_read_text(path: Path, max_bytes: int = 1_000_000) -> str:
    """Read a text file safely without crashing on encoding problems or huge files."""
    if not path.exists() or not path.is_file():
        return ""
    if path.stat().st_size > max_bytes:
        return ""
    try:
        return path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return ""


def relative_posix(path: Path, root: Path) -> str:
    """Return a stable POSIX-style relative path for reports."""
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()


def normalize_package_name(requirement: str) -> str:
    """Normalize a requirement line to a package name for duplicate detection."""
    cleaned = requirement.strip().split("#", 1)[0].strip()
    cleaned = re.split(r"[<>=!~\[]", cleaned, maxsplit=1)[0]
    return cleaned.lower().replace("_", "-").strip()


def ensure_directory(path: Path) -> Path:
    """Create and return a directory."""
    path.mkdir(parents=True, exist_ok=True)
    return path


def looks_like_github_url(value: str) -> bool:
    """Return True if input is a clean public GitHub repository URL."""
    return bool(GITHUB_URL_RE.match(value.strip()))


def remove_tree(path: Path) -> None:
    """Best-effort recursive directory deletion."""
    if path.exists():
        shutil.rmtree(path, ignore_errors=True)


def is_generated_python_source(path: Path) -> bool:
    """Return True for common generated/vendor Python files that distort maintainability scores."""
    lowered_parts = {part.lower() for part in path.parts}
    generated_dirs = {"vendor", "vendors", "third_party", "third-party", "generated", ".generated", "build"}
    if lowered_parts.intersection(generated_dirs):
        return True

    name = path.name.lower()
    generated_suffixes = ("_pb2.py", "_pb2_grpc.py", "_ui.py", "_rc.py")
    if name.endswith(generated_suffixes):
        return True

    header = safe_read_text(path, max_bytes=8_000).lower()[:1_200]
    generated_markers = ("generated by", "auto-generated", "autogenerated", "do not edit")
    return any(marker in header for marker in generated_markers)
